services:
  - type: web
    name: kids-games
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /api/health
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
