export interface Animal {
  id: string;
  name: string;
  emoji: string;
}

export const ANIMALS: Animal[] = [
  { id: 'lion', name: 'אריה', emoji: '🦁' },
  { id: 'elephant', name: 'פיל', emoji: '🐘' },
  { id: 'giraffe', name: "ג'ירפה", emoji: '🦒' },
  { id: 'zebra', name: 'זברה', emoji: '🦓' },
  { id: 'monkey', name: 'קוף', emoji: '🐒' },
  { id: 'tiger', name: 'טיגריס', emoji: '🐅' },
  { id: 'bear', name: 'דוב', emoji: '🐻' },
  { id: 'panda', name: 'פנדה', emoji: '🐼' },
  { id: 'kangaroo', name: 'קנגורו', emoji: '🦘' },
  { id: 'crocodile', name: 'תנין', emoji: '🐊' },
  { id: 'turtle', name: 'צב', emoji: '🐢' },
  { id: 'dolphin', name: 'דולפין', emoji: '🐬' },
  { id: 'whale', name: 'לווייתן', emoji: '🐋' },
  { id: 'shark', name: 'כריש', emoji: '🦈' },
  { id: 'octopus', name: 'תמנון', emoji: '🐙' },
  { id: 'penguin', name: 'פינגווין', emoji: '🐧' },
  { id: 'owl', name: 'ינשוף', emoji: '🦉' },
  { id: 'parrot', name: 'תוכי', emoji: '🦜' },
  { id: 'butterfly', name: 'פרפר', emoji: '🦋' },
  { id: 'bee', name: 'דבורה', emoji: '🐝' },
  { id: 'snake', name: 'נחש', emoji: '🐍' },
  { id: 'horse', name: 'סוס', emoji: '🐎' },
  { id: 'cow', name: 'פרה', emoji: '🐄' },
  { id: 'sheep', name: 'כבשה', emoji: '🐑' },
  { id: 'rabbit', name: 'ארנב', emoji: '🐇' },
  { id: 'fox', name: 'שועל', emoji: '🦊' },
  { id: 'hedgehog', name: 'קיפוד', emoji: '🦔' },
  { id: 'camel', name: 'גמל', emoji: '🐫' },
  { id: 'hippo', name: 'היפופוטם', emoji: '🦛' },
  { id: 'rhino', name: 'קרנף', emoji: '🦏' },
  { id: 'duck', name: 'ברווז', emoji: '🦆' },
  { id: 'rooster', name: 'תרנגול', emoji: '🐓' },
  { id: 'frog', name: 'צפרדע', emoji: '🐸' },
  { id: 'cat', name: 'חתול', emoji: '🐈' },
  { id: 'dog', name: 'כלב', emoji: '🐕' },
  { id: 'wolf', name: 'זאב', emoji: '🐺' },
  { id: 'squirrel', name: 'סנאי', emoji: '🐿️' },
  { id: 'bat', name: 'עטלף', emoji: '🦇' },
  { id: 'flamingo', name: 'פלמינגו', emoji: '🦩' },
  { id: 'peacock', name: 'טווס', emoji: '🦚' },
  { id: 'snail', name: 'חילזון', emoji: '🐌' },
  { id: 'crab', name: 'סרטן', emoji: '🦀' },
];
